server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/products?createDatabaseIfNotExist=true&autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      platform: mysql